import {
  pgTable,
  serial,
  text,
  varchar,
  integer,
  timestamp,
  json,
  pgEnum,
} from "drizzle-orm/pg-core";

// Enums PostgreSQL
export const taskStatusEnum = pgEnum("task_status", [
  "todo",
  "in_progress",
  "done",
]);

export const letterTypeEnum = pgEnum("letter_type", [
  "cancellation",
  "complaint",
  "reimbursement",
  "admin_request",
]);

// Table Users
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  openId: text("open_id").notNull().unique(),
  name: text("name"),
  email: text("email"),
  loginMethod: text("login_method"),
  country: text("country"),
  ageGroup: text("age_group"),
  role: text("role").default("user"),
  lastSignedIn: timestamp("last_signed_in").defaultNow(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/** Procedures saved by a user from the catalog (personal copy with progress). */
export const savedProcedures = pgTable("saved_procedures", {
  id: serial("id").primaryKey(),
  userId: integer("userId").notNull(),
  /** Catalog procedure key, e.g. "health-rdv-medecin" */
  procedureKey: varchar("procedureKey", { length: 128 }).notNull(),
  /** JSON array of completed step indices */
  completedSteps: json("completedSteps"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull(),
});

export type SavedProcedure = typeof savedProcedures.$inferSelect;

/** In-progress life admin tasks tracked on the dashboard. */
export const userTasks = pgTable("user_tasks", {
  id: serial("id").primaryKey(),
  userId: integer("userId").notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description"),
  /** Optional deadline (unix ms) */
  deadlineAt: integer("deadlineAt"),
  status: taskStatusEnum("status").default("todo").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull(),
});

export type UserTask = typeof userTasks.$inferSelect;

/** Documents/letters generated by the letter generator. */
export const generatedLetters = pgTable("generated_letters", {
  id: serial("id").primaryKey(),
  userId: integer("userId").notNull(),
  /** Letter type: cancellation | complaint | reimbursement | admin_request */
  letterType: letterTypeEnum("letterType").notNull(),
  title: varchar("title", { length: 255 }),
  /** Full generated letter text (markdown/plain) */
  content: text("content"),
  /** JSON of the form inputs used */
  formData: json("formData"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type GeneratedLetter = typeof generatedLetters.$inferSelect;