import {
  int,
  json,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extended with profile fields for LifeCopilot (age group, country).
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId). Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  /** LifeCopilot profile fields */
  ageGroup: mysqlEnum("ageGroup", ["junior", "teen", "adult", "senior"]),
  country: varchar("country", { length: 128 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/** Procedures saved by a user from the catalog (personal copy with progress). */
export const savedProcedures = mysqlTable("saved_procedures", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  /** Catalog procedure key, e.g. "health-rdv-medecin" */
  procedureKey: varchar("procedureKey", { length: 128 }).notNull(),
  /** JSON array of completed step indices */
  completedSteps: json("completedSteps"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type SavedProcedure = typeof savedProcedures.$inferSelect;

/** In-progress life admin tasks tracked on the dashboard. */
export const userTasks = mysqlTable("user_tasks", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description"),
  /** Optional deadline (unix ms) */
  deadlineAt: int("deadlineAt"),
  status: mysqlEnum("status", ["todo", "in_progress", "done"]).default("todo").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type UserTask = typeof userTasks.$inferSelect;

/** Documents/letters generated by the letter generator. */
export const generatedLetters = mysqlTable("generated_letters", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  /** Letter type: cancellation | complaint | reimbursement | admin_request */
  letterType: mysqlEnum("letterType", [
    "cancellation",
    "complaint",
    "reimbursement",
    "admin_request",
  ]).notNull(),
  title: varchar("title", { length: 255 }),
  /** Full generated letter text (markdown/plain) */
  content: text("content"),
  /** JSON of the form inputs used */
  formData: json("formData"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type GeneratedLetter = typeof generatedLetters.$inferSelect;
